name: sbmcal
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - astromatic-source-extractor=2.25.0
  - astromatic-swarp=2.38.0
  - astropy=4.2.1
  - astroquery=0.4.3
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.3.7
  - emcee=3.1.0
  - entrypoints=0.3
  - esutil=0.6.8
  - expat=2.4.4
  - fftw=3.3.9
  - fitsio=1.1.4
  - freetype=2.11.0
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - h5py=3.6.0
  - hdf5=1.10.6
  - html5lib=1.1
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.17.0
  - jinja2=3.0.2
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - keyring=23.4.0
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - llvmlite=0.37.0
  - lsstdesc.coord=1.2.2
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - meds=0.9.14
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - ngmix=1.3.9
  - notebook=6.4.8
  - numba=0.54.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - openssl=1.1.1l
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pudb=2019.2
  - pybind11=2.9.1
  - pycparser=2.21
  - pyerfa=2.0.0
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.2
  - python-mimeparse=1.6.0
  - python_abi=3.7
  - pytz=2021.3
  - pyvo=1.1
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtpy=1.11.2
  - readline=8.1.2
  - requests=2.27.1
  - schwimmbad=0.3.2
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.37.2
  - tbb=2021.5.0
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - urllib3=1.26.8
  - urwid=2.1.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - biggles==1.7.2
    - data==0.4
    - ete3==3.1.2
    - funcsigs==1.0.2
    - galsim==2.3.4
    - iminuit==2.9.0
    - joblib==1.1.0
    - latex==0.7.0
    - mof==0.1.1
    - nose==1.3.7
    - piff==1.2.0
    - psfex==0.4.0
    - scikit-learn==1.0.2
    - shutilwhich==1.1.0
    - tempdir==0.7.1
    - threadpoolctl==3.1.0
    - treecorr==4.2.6
    - treegp==0.6.0
