# Output directories
# ------------------
output_file:            "./ngmix_output.dat"
diagnostic_dir:         "./diagnostics_plots"

# Input
# -----
meds_file:              "../../Medsmaker/output/test.meds"

# Parameters
# ----------
start_index:            null            # 1st object to analyze (null for start)
end_index:              null            # last object to analyze (null for end)
psf_model:              "gauss"         # PSF model: gauss or em
gal_model:              "exp"           # Galaxy model: exp
