galsim:
  clobber: true
  config_dir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/superbit_lensing/galsim/config_files
  config_file: pipe_test.yaml
  outdir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
medsmaker:
  fname_base: pipe_test
  mock_dir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
  outdir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
  outfile: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/pipe_test_meds.fits
  run_name: pipe_test
metacal:
  end: 2500
  meds_file: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/pipe_test_meds.fits
  outdir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
  outfile: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/pipe_test_mcal.fits
ngmix_fit:
  config: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/ngmix_test.yaml
  end: 100
  meds_file: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/pipe_test_meds.fits
  outdir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
  outfile: pipe_test_ngmix.fits
run_options:
  ncores: 8
  order:
  - galsim
  - medsmaker
  - metacal
  - shear_profile
  - ngmix_fit
  outdir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
  run_diagnostics: true
  run_name: pipe_test
  vb: true
shear_profile:
  mcal_file: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/pipe_test_mcal.fits
  outdir: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test
  outfile: pipe_test_annular.fits
  overwrite: true
  run_name: pipe_test
  se_file: /gpfs/data/idellant/jmcclear/superbit/superbit-metacal/tests/pipe_test/pipe_test_mock_coadd_cat.ldac
