galsim:
  clobber: true
  config_dir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/galsim/config_files
  config_file: superbit_parameters_forecast.yaml
  outdir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/tests/pipe_test
  
medsmaker:
  # These are config parameters for: superbit-metacal/superbit_lensing/scripts/process_mocsk.py
  # :mock_dir: directory from which to access mock images
  # :fname_base: what is the base filename for mock images;
  #      --> do NOT append "fits", wildcards, etc. to end. Code does that for you.
  # :outdir: directory for all output files (MEDS, catalogs, images, etc.)
  # :outfile: name of output MEDS file, default behavior is storage in ???
  
  mock_dir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/tests/pipe_test
  fname_base: pipe_test
  outdir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/pipe_test2
  outfile: pipe_test2.meds

  
metacal:
  # :plot: make diagnostics plots, saved in '{outdir}/plots/metacalibration/'
  start: 0
  end: 200
  medsfile: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/pipe_test2/pipe_test2.meds
  outdir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/pipe_test2
  outfile: pipe_test2_mcal.fits
  plot: True 
  
run_options:
  ncores:
  order:
  #- galsim
  #  - medsmaker
  - metacal
  run_diagnostics: true
  run_name: pipe_test2
  vb: true
