galsim:
  clobber: true
  config_dir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/galsim/config_files
  config_file: superbit_parameters_forecast.yaml
  outdir: /Users/jemcclea/Research/SuperBIT/superbit-metacal/superbit_lensing/tests/pipe_test2
  
medsmaker:
  # These are config parameters for: superbit-metacal/superbit_lensing/scripts/process_mocks.py
  # :mock_dir: directory from which to access mock images
  # :fname_base: what is the base filename for mock images;
  #      --> do NOT append "fits", wildcards, etc. to end. Code does that for you.
  # :outdir: directory for all output files (MEDS, catalogs, images, etc.)
  # :outfile: name of output MEDS file, default behavior is storage in ???
  
  mock_dir: /Users/jemcclea/Research/SuperBIT/mock_forecasting_data/cluster5/round*
  fname_base: superbit_gaussJitter
  outdir: /Users/jemcclea/Research/SuperBIT/forecasting_analysis/psfex_test/
  #outdir: ./pipe_sexparam_tests/sigthresh1.1_minarea5/metacal
  outfile: sigthresh1.1_minarea5.meds

  
metacal:
  # :plot: Boolean condition to create diagnostics plots, saved in '{outdir}/plots/metacalibration/'
  #        ["True"/"False", default="True"]
  
  start: 6000
  end: 6020
  medsfile: /Users/jemcclea/Research/SuperBIT/forecasting_analysis/psfex_test/sigthresh1.1_minarea5.meds
  outdir: /Users/jemcclea/Research/SuperBIT/forecasting_analysis/psfex_test/metacal
  outfile: galsim_des_psfex_mcalfitting.fits
  plot: True 
  
run_options:
  ncores: 1
  order:
  #- galsim
  #- medsmaker
  - metacal
  run_diagnostics: true
  run_name: psfex_tests
  vb: true
